# Generated by Django 5.2.7 on 2026-01-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_managements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='nome',
        ),
        migrations.AddField(
            model_name='conta',
            name='conta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
