# Generated by Django 5.2.7 on 2026-01-13 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_managements', '0002_remove_conta_nome_conta_conta_alter_conta_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='descricao',
            field=models.CharField(default=django.utils.timezone.now, verbose_name=50),
            preserve_default=False,
        ),
    ]
