# Generated by Django 5.2.7 on 2026-01-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_managements', '0003_deposito_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposito',
            name='hora',
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
