# Generated by Django 5.2.7 on 2026-01-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_managements', '0004_remove_deposito_hora_alter_conta_saldo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo_geral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_geral', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='levantamento',
            name='hora',
        ),
        migrations.AddField(
            model_name='levantamento',
            name='descricao',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='levantamento',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='levantamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
