# Generated by Django 5.2.7 on 2026-01-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_managements', '0005_saldo_geral_remove_levantamento_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='movimento',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='movimento',
            name='valor',
        ),
        migrations.AddField(
            model_name='movimento',
            name='movimento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimento',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_managements.conta'),
        ),
    ]
