# Generated by Django 5.2.7 on 2026-01-18 12:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_managements', '0006_remove_movimento_data_remove_movimento_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levantamento',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='movimento',
            name='movimento',
        ),
        migrations.AddField(
            model_name='movimento',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimento',
            name='descricao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='tipo',
            field=models.CharField(choices=[('Deposito', 'DEPOSITO'), ('Levantamento', 'LEVANTAMENTO')], default='DEPOSITO', max_length=12),
        ),
        migrations.AddField(
            model_name='movimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimento',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='money_managements.conta'),
        ),
        migrations.DeleteModel(
            name='Deposito',
        ),
        migrations.DeleteModel(
            name='Levantamento',
        ),
    ]
